/**:
  ros__parameters:
    device: cuda:0
    # Extended verbosity on info logs. Show logs with number of detections and more
    verbose_info_logs: false
    # Specifies whether to use depth images for pose refinement. If set to `true` all cameras are expected to provide depth images
    use_depth: false
    # Specifies which pose estimator to use in the pipeline
    pose_estimator_type: "cosypose"
    # Specifies if the combined segmentation mask should be published.
    publish_seg_masks: true
    cosypose:
      # Name of BOP dataset, used to load specific weights and object models
      dataset_name: $(var dataset_name)
      # Type of neural network model to use. Available 'pbr'|'synth+real'
      model_type: "pbr"
    camera_names: ["cam_1"]
    cameras:
      cam_1:
        leading: true
    